import{createRequire}from'node:module';
import assert from'node:assert/strict';
const require=createRequire(import.meta.url);
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require(process.env.PLAYWRIGHT_PATH||process.env.USERPROFILE+'/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext({viewport:{width:1440,height:1050},deviceScaleFactor:1});
const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:8788';
const health=await (await fetch(base+'/api/health')).json();assert.ok(health.ephemeral,'Browser tests require an --ephemeral server');
await page.goto(base,{waitUntil:'networkidle'});await page.waitForFunction(()=>!!window.orbis);
await page.evaluate(async()=>{const {createState}=await import('/js/engine.js');const saved=await (await fetch('/api/save')).json();const c=orbis.context;const next=createState(c.facilities,c.seaRouter,c.environment);await fetch('/api/save',{method:'PUT',headers:{'Content-Type':'application/json','X-Orbis-Client':'1'},body:JSON.stringify({revision:saved.revision,state:next})});});
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!window.orbis);
assert.equal(await page.locator('#jobs-table tr').count(),9);
await page.locator('#destination-input').fill('LAX');
await page.locator('#destination-results [data-facility]:not(:disabled)').first().click();
assert.ok((await page.locator('#route-estimate').innerText()).includes('10,'));
await page.locator('#draw-route').click();
await page.locator('#map').click({position:{x:510,y:170}});
assert.equal(await page.locator('#waypoint-count').innerText(),'1');
await page.locator('#clear-route').click();await page.keyboard.press('Escape');
await page.locator('#fuel-slider').fill('10');await page.locator('#fuel-slider').dispatchEvent('input');
assert.ok((await page.locator('#route-warnings').innerText()).includes('燃油缺口'));
await page.locator('#dispatch-button').click();
await page.waitForFunction(()=>orbis.state.jobs.length===10);
assert.equal(await page.evaluate(()=>orbis.state.fleet.length),8);
console.log('PASS search, custom waypoint, fuel warnings, dispatch and lease');
await page.locator('#advance-button').click();
assert.ok(await page.evaluate(()=>orbis.state.hour>=5.999));
assert.ok(await page.evaluate(()=>orbis.state.jobs.some(j=>j.diversions>0||j.status==='stranded')));
await page.locator('#events-button').click();
assert.ok((await page.locator('#modal-content').innerText()).includes('燃油'));
await page.locator('#close-modal').click();
console.log('PASS simulation progression and actual incident history');
await page.locator('[data-mode="sea"]').click();
await page.waitForFunction(()=>orbis.plan.charted);
assert.ok(await page.evaluate(()=>orbis.plan.path.length>10));
await page.locator('#auto-route').click();
for(const layer of['weather','currents','risk'])await page.locator('[data-layer="'+layer+'"]').click();
await page.locator('[data-view="intel"]').click();
assert.ok((await page.locator('#modal-content').innerText()).includes('12 个真实小时'));
await page.locator('[data-action="policy"]').click();await page.locator('#policy-name').fill('测试海峡');await page.locator('#policy-kind').selectOption('sea');await page.locator('[data-action="add-policy"]').click();
assert.ok(await page.evaluate(()=>orbis.state.scenarioZones.some(z=>z.name.includes('测试海峡'))));
console.log('PASS maritime route and dynamic policy layer');
await page.locator('[data-filter="air"]').click();
const activeId=await page.evaluate(()=>orbis.state.jobs.find(j=>j.status==='active'&&j.kind==='air')?.id);
assert.ok(activeId);
await page.locator('[data-job="'+activeId+'"]').click();
await page.locator('[data-action="edit-job"]').click();
assert.equal(await page.locator('#origin-input').isDisabled(),true);
await page.locator('#dispatch-button').click();
assert.ok(await page.evaluate(()=>orbis.state.events.some(e=>e.title.includes('航线已修改'))));
console.log('PASS in-flight route takeover');
await page.locator('#save-button').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('保存'));
const before=await page.evaluate(()=>({jobs:orbis.state.jobs.length,hour:orbis.state.hour}));
await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>!!window.orbis);
assert.deepEqual(await page.evaluate(()=>({jobs:orbis.state.jobs.length,hour:orbis.state.hour})),before);
assert.equal(await page.evaluate(()=>orbis.state.speed),0);
console.log('PASS saved progress survives reload and resumes paused');
await page.screenshot({path:'work/qa/desktop-play.png',fullPage:true});
await page.locator('[data-view="company"]').click();assert.ok((await page.locator('#modal-content').innerText()).includes('存档管理'));await page.locator('#close-modal').click();
await page.setViewportSize({width:390,height:844});await page.locator('#fit-map').click();
await page.screenshot({path:'work/qa/mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
assert.equal(errors.length,0,errors.join('\n'));
console.log('PASS responsive mobile layout, all panels, no JavaScript errors');
await browser.close();
